language: cpp
dist: trusty

cache:
  directories:
    - $HOME/.ccache
    - $HOME/deps

addons:
  apt:
    update: true
    sources: &default_sources
      - ubuntu-toolchain-r-test
    packages: &default_packages
      - libc++-dev
      - libc++abi-dev
      - autotools-dev
      - autoconf
      - libtool
      
branches:
  only:
    - master

matrix:
  include:

    - os: linux
      compiler: gcc
      env: CXX_NAME='g++-6'
      addons: {apt: { packages: [*default_packages, g++-6], sources: [*default_sources]}}

    - os: linux
      compiler: gcc
      env: CXX_NAME='g++-6' CMAKE_BUILD_TYPE=Debug
      addons: {apt: { packages: [*default_packages, g++-6], sources: [*default_sources]}}

    - os: linux
      compiler: gcc
      env: CXX_NAME='g++-7'
      addons: {apt: { packages: [*default_packages, g++-7], sources: [*default_sources]}}

    - os: linux
      compiler: clang
      env: CXX_NAME='clang++-6.0' CC_NAME='clang-6.0'
      addons: {apt: { packages: [*default_packages, clang-6.0], sources: [*default_sources, llvm-toolchain-trusty-6.0]}}

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CXX_NAME='c++'

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: CXX_NAME='c++'

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: CXX_NAME='clang++'

before_install:
  # Check commit matches expected commit (because of Travis bug)
  - if [[ "$TRAVIS_COMMIT" != "$(git rev-parse HEAD)" ]]; then echo "Commit doesn't match expected $TRAVIS_COMMIT"; fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$CXX_NAME" == "clang++" ]]; then
      brew install --with-clang llvm@6
      brew link --force --overwrite llvm@6
    fi

  # This is required to override Travis's definitions of CC and CXX that lead to old Ubuntu-packaged compilers
  - export CXX="$CXX_NAME"
  - export CC="$CC_NAME"
  - |
    cd $HOME/deps/
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update
      sudo apt-get install -y libgtest-dev cmake
    fi

script:
  - cd $TRAVIS_BUILD_DIR
  - export GTEST_LOC=$HOME/deps
  - export BOOST_ROOT=$HOME/deps/boost_1_66_0
  - export TRNG_LOC=$HOME/deps/trng
  - ./install.sh
  - cd build/installed/bin && ./tests